// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW0cduRar9TJbHEzoxSG0AM09kHXVUzHc',
    appId: '1:528774060892:web:9343969ca19f2d47547f99',
    messagingSenderId: '528774060892',
    projectId: 'servicemanager-43bad',
    authDomain: 'servicemanager-43bad.firebaseapp.com',
    storageBucket: 'servicemanager-43bad.appspot.com',
    measurementId: 'G-YXLDJ66D9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj1aJDrE1XIZe5kvu-8fsR3_ADQ-qXPU8',
    appId: '1:528774060892:android:a2a65058a5213c1d547f99',
    messagingSenderId: '528774060892',
    projectId: 'servicemanager-43bad',
    storageBucket: 'servicemanager-43bad.appspot.com',
  );

}